### ISSUE TITLE
help for codes

### ISSUE THREAD

**Issue by wh954** [ludlows/CSI-Activity-Recognition#2]
Thanks for sharing this project, this is great!
I have a question: What part of this paper"A Survey on Behaviour Recognition Using WiFi Channel State Information" has your code modified?

**Comment by ludlows** [comment]
Thanks for your interests.
the preprocessing part is same although I have clean up some lines of codes.
about the DL model, I add attention layer to get better results.

**Comment by wh954** [comment]
Thanks for your reply!
Well,which or several functions of the original project can be replaced by the functions "csi_model" writed by you?

**Comment by ludlows** [comment]
you need to check the original project part involving DL models.
As I remember, it was using LSTM only.

**Comment by beyond96** [comment]
Many thanks！
But I failed to run the original codes？Would you mind sharing your complete codes.
I have stuck on these question few days.
I am so sorry to disturb you.
My email address is 2474575544@qq.com &nbsp; &nbsp;
or cth_wu@mail.scut.edu.cn


All responses will be appreciated！


发自我的iPhone


------------------ Original ------------------

**Comment by beyond96** [comment]
Many thanks！
But I failed to run the original codes.Would you mind sharing your complete codes?
I have stuck on these question few days.
I am so sorry to disturb you.
My email address is 2474575544@qq.com &nbsp; &nbsp;
or cth_wu@mail.scut.edu.cn


All responses will be appreciated！

**Comment by ludlows** [comment]
you need to solve the problems in the original codes by yourself, although that part in my code can work if you have read it carefully.
the way to do research is not asking for results.
you should find the problem and solve it.
